// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Ship.proto

#include "Ship.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>

extern PROTOBUF_INTERNAL_EXPORT_Ship_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_BulkCargo_Ship_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Ship_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ShipData_Ship_2eproto;
extern PROTOBUF_INTERNAL_EXPORT_Ship_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Unit_Ship_2eproto;
namespace ship {
class ShipDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ShipData> _instance;
} _ShipData_default_instance_;
class UnitDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Unit> _instance;
} _Unit_default_instance_;
class BulkCargoDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<BulkCargo> _instance;
} _BulkCargo_default_instance_;
class ShipBodyDataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ShipBodyData> _instance;
} _ShipBodyData_default_instance_;
}  // namespace ship
static void InitDefaultsShipData_Ship_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ship::_ShipData_default_instance_;
    new (ptr) ::ship::ShipData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ship::ShipData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ShipData_Ship_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsShipData_Ship_2eproto}, {}};

static void InitDefaultsUnit_Ship_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ship::_Unit_default_instance_;
    new (ptr) ::ship::Unit();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ship::Unit::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Unit_Ship_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUnit_Ship_2eproto}, {}};

static void InitDefaultsBulkCargo_Ship_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ship::_BulkCargo_default_instance_;
    new (ptr) ::ship::BulkCargo();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ship::BulkCargo::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_BulkCargo_Ship_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsBulkCargo_Ship_2eproto}, {}};

static void InitDefaultsShipBodyData_Ship_2eproto() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::ship::_ShipBodyData_default_instance_;
    new (ptr) ::ship::ShipBodyData();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::ship::ShipBodyData::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<3> scc_info_ShipBodyData_Ship_2eproto =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 3, InitDefaultsShipBodyData_Ship_2eproto}, {
      &scc_info_ShipData_Ship_2eproto.base,
      &scc_info_Unit_Ship_2eproto.base,
      &scc_info_BulkCargo_Ship_2eproto.base,}};

void InitDefaults_Ship_2eproto() {
  ::google::protobuf::internal::InitSCC(&scc_info_ShipData_Ship_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Unit_Ship_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_BulkCargo_Ship_2eproto.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ShipBodyData_Ship_2eproto.base);
}

::google::protobuf::Metadata file_level_metadata_Ship_2eproto[4];
const ::google::protobuf::EnumDescriptor* file_level_enum_descriptors_Ship_2eproto[1];
constexpr ::google::protobuf::ServiceDescriptor const** file_level_service_descriptors_Ship_2eproto = nullptr;

const ::google::protobuf::uint32 TableStruct_Ship_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, shipname_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, loa_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, height_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, beam_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, deckstr_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, mindraft_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, maxdraft_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, maxdwt_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, lcglight_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, tcglight_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, vcglight_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, lightship_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, watercondition_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipData, tankstr_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ship::Unit, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ship::Unit, name_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, lcg_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, tcg_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, vcg_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, length_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, breadth_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, height_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, density_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, volume_),
  PROTOBUF_FIELD_OFFSET(::ship::Unit, type_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, name_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, lcg_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, tcg_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, vcg_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, length_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, breadth_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, height_),
  PROTOBUF_FIELD_OFFSET(::ship::BulkCargo, weight_),
  ~0u,  // no _has_bits_
  PROTOBUF_FIELD_OFFSET(::ship::ShipBodyData, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  PROTOBUF_FIELD_OFFSET(::ship::ShipBodyData, shipdata_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipBodyData, unit_),
  PROTOBUF_FIELD_OFFSET(::ship::ShipBodyData, bulk_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::ship::ShipData)},
  { 19, -1, sizeof(::ship::Unit)},
  { 34, -1, sizeof(::ship::BulkCargo)},
  { 47, -1, sizeof(::ship::ShipBodyData)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::ship::_ShipData_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ship::_Unit_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ship::_BulkCargo_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::ship::_ShipBodyData_default_instance_),
};

::google::protobuf::internal::AssignDescriptorsTable assign_descriptors_table_Ship_2eproto = {
  {}, AddDescriptors_Ship_2eproto, "Ship.proto", schemas,
  file_default_instances, TableStruct_Ship_2eproto::offsets,
  file_level_metadata_Ship_2eproto, 4, file_level_enum_descriptors_Ship_2eproto, file_level_service_descriptors_Ship_2eproto,
};

const char descriptor_table_protodef_Ship_2eproto[] =
  "\n\nShip.proto\022\004ship\"\376\001\n\010ShipData\022\020\n\010ShipN"
  "ame\030\001 \001(\t\022\013\n\003LOA\030\002 \001(\002\022\016\n\006height\030\003 \001(\002\022\014"
  "\n\004beam\030\004 \001(\002\022\017\n\007deckStr\030\005 \001(\002\022\020\n\010MinDraf"
  "t\030\006 \001(\002\022\020\n\010MaxDraft\030\007 \001(\002\022\016\n\006MaxDWT\030\010 \001("
  "\005\022\020\n\010LCGLight\030\t \001(\002\022\020\n\010TCGLight\030\n \001(\002\022\020\n"
  "\010VCGLight\030\013 \001(\002\022\021\n\tlightShip\030\014 \001(\005\022\026\n\016wa"
  "terCondition\030\r \001(\002\022\017\n\007tankStr\030\016 \001(\002\"\217\002\n\004"
  "Unit\022\014\n\004Name\030\001 \001(\t\022\013\n\003lcg\030\002 \001(\002\022\013\n\003tcg\030\003"
  " \001(\002\022\013\n\003vcg\030\004 \001(\002\022\016\n\006length\030\005 \001(\002\022\017\n\007bre"
  "adth\030\006 \001(\002\022\016\n\006height\030\007 \001(\002\022\017\n\007density\030\010 "
  "\001(\002\022\016\n\006volume\030\t \001(\002\022!\n\004type\030\014 \001(\0162\023.ship"
  ".Unit.UnitType\"]\n\010UnitType\022\013\n\007BALLAST\020\000\022"
  "\014\n\010CARGODRY\020\001\022\r\n\tCARGOTANK\020\002\022\007\n\003HFO\020\003\022\006\n"
  "\002DO\020\004\022\006\n\002LO\020\005\022\006\n\002FW\020\006\022\006\n\002VA\020\007\"\201\001\n\tBulkCa"
  "rgo\022\014\n\004Name\030\001 \001(\t\022\013\n\003lcg\030\002 \001(\002\022\013\n\003tcg\030\003 "
  "\001(\002\022\013\n\003vcg\030\004 \001(\002\022\016\n\006length\030\005 \001(\002\022\017\n\007brea"
  "dth\030\006 \001(\002\022\016\n\006height\030\007 \001(\002\022\016\n\006weight\030\t \001("
  "\002\"i\n\014ShipBodyData\022 \n\010shipdata\030\001 \003(\0132\016.sh"
  "ip.ShipData\022\030\n\004unit\030\002 \003(\0132\n.ship.Unit\022\035\n"
  "\004bulk\030\006 \003(\0132\017.ship.BulkCargob\006proto3"
  ;
::google::protobuf::internal::DescriptorTable descriptor_table_Ship_2eproto = {
  false, InitDefaults_Ship_2eproto, 
  descriptor_table_protodef_Ship_2eproto,
  "Ship.proto", &assign_descriptors_table_Ship_2eproto, 796,
};

void AddDescriptors_Ship_2eproto() {
  static constexpr ::google::protobuf::internal::InitFunc deps[1] =
  {
  };
 ::google::protobuf::internal::AddDescriptors(&descriptor_table_Ship_2eproto, deps, 0);
}

// Force running AddDescriptors() at dynamic initialization time.
static bool dynamic_init_dummy_Ship_2eproto = []() { AddDescriptors_Ship_2eproto(); return true; }();
namespace ship {
const ::google::protobuf::EnumDescriptor* Unit_UnitType_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&assign_descriptors_table_Ship_2eproto);
  return file_level_enum_descriptors_Ship_2eproto[0];
}
bool Unit_UnitType_IsValid(int value) {
  switch (value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
    case 6:
    case 7:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Unit_UnitType Unit::BALLAST;
const Unit_UnitType Unit::CARGODRY;
const Unit_UnitType Unit::CARGOTANK;
const Unit_UnitType Unit::HFO;
const Unit_UnitType Unit::DO;
const Unit_UnitType Unit::LO;
const Unit_UnitType Unit::FW;
const Unit_UnitType Unit::VA;
const Unit_UnitType Unit::UnitType_MIN;
const Unit_UnitType Unit::UnitType_MAX;
const int Unit::UnitType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

// ===================================================================

void ShipData::InitAsDefaultInstance() {
}
class ShipData::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ShipData::kShipNameFieldNumber;
const int ShipData::kLOAFieldNumber;
const int ShipData::kHeightFieldNumber;
const int ShipData::kBeamFieldNumber;
const int ShipData::kDeckStrFieldNumber;
const int ShipData::kMinDraftFieldNumber;
const int ShipData::kMaxDraftFieldNumber;
const int ShipData::kMaxDWTFieldNumber;
const int ShipData::kLCGLightFieldNumber;
const int ShipData::kTCGLightFieldNumber;
const int ShipData::kVCGLightFieldNumber;
const int ShipData::kLightShipFieldNumber;
const int ShipData::kWaterConditionFieldNumber;
const int ShipData::kTankStrFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ShipData::ShipData()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ship.ShipData)
}
ShipData::ShipData(const ShipData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  shipname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.shipname().size() > 0) {
    shipname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shipname_);
  }
  ::memcpy(&loa_, &from.loa_,
    static_cast<size_t>(reinterpret_cast<char*>(&tankstr_) -
    reinterpret_cast<char*>(&loa_)) + sizeof(tankstr_));
  // @@protoc_insertion_point(copy_constructor:ship.ShipData)
}

void ShipData::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ShipData_Ship_2eproto.base);
  shipname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&loa_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tankstr_) -
      reinterpret_cast<char*>(&loa_)) + sizeof(tankstr_));
}

ShipData::~ShipData() {
  // @@protoc_insertion_point(destructor:ship.ShipData)
  SharedDtor();
}

void ShipData::SharedDtor() {
  shipname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ShipData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ShipData& ShipData::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ShipData_Ship_2eproto.base);
  return *internal_default_instance();
}


void ShipData::Clear() {
// @@protoc_insertion_point(message_clear_start:ship.ShipData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  shipname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&loa_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&tankstr_) -
      reinterpret_cast<char*>(&loa_)) + sizeof(tankstr_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ShipData::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ShipData*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string ShipName = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("ship.ShipData.ShipName");
        object = msg->mutable_shipname();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // float LOA = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_loa(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float height = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_height(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float beam = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 37) goto handle_unusual;
        msg->set_beam(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float deckStr = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 45) goto handle_unusual;
        msg->set_deckstr(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float MinDraft = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 53) goto handle_unusual;
        msg->set_mindraft(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float MaxDraft = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 61) goto handle_unusual;
        msg->set_maxdraft(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // int32 MaxDWT = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 64) goto handle_unusual;
        msg->set_maxdwt(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // float LCGLight = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 77) goto handle_unusual;
        msg->set_lcglight(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float TCGLight = 10;
      case 10: {
        if (static_cast<::google::protobuf::uint8>(tag) != 85) goto handle_unusual;
        msg->set_tcglight(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float VCGLight = 11;
      case 11: {
        if (static_cast<::google::protobuf::uint8>(tag) != 93) goto handle_unusual;
        msg->set_vcglight(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // int32 lightShip = 12;
      case 12: {
        if (static_cast<::google::protobuf::uint8>(tag) != 96) goto handle_unusual;
        msg->set_lightship(::google::protobuf::internal::ReadVarint(&ptr));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      // float waterCondition = 13;
      case 13: {
        if (static_cast<::google::protobuf::uint8>(tag) != 109) goto handle_unusual;
        msg->set_watercondition(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float tankStr = 14;
      case 14: {
        if (static_cast<::google::protobuf::uint8>(tag) != 117) goto handle_unusual;
        msg->set_tankstr(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ShipData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ship.ShipData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string ShipName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_shipname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->shipname().data(), static_cast<int>(this->shipname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ship.ShipData.ShipName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float LOA = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &loa_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float height = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float beam = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (37 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &beam_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float deckStr = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (45 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &deckstr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float MinDraft = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (53 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &mindraft_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float MaxDraft = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (61 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &maxdraft_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 MaxDWT = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (64 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &maxdwt_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float LCGLight = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (77 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &lcglight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float TCGLight = 10;
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (85 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &tcglight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float VCGLight = 11;
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (93 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vcglight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 lightShip = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (96 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &lightship_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float waterCondition = 13;
      case 13: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (109 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &watercondition_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float tankStr = 14;
      case 14: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (117 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &tankstr_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ship.ShipData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ship.ShipData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ShipData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ship.ShipData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ShipName = 1;
  if (this->shipname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->shipname().data(), static_cast<int>(this->shipname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ship.ShipData.ShipName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->shipname(), output);
  }

  // float LOA = 2;
  if (this->loa() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->loa(), output);
  }

  // float height = 3;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->height(), output);
  }

  // float beam = 4;
  if (this->beam() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->beam(), output);
  }

  // float deckStr = 5;
  if (this->deckstr() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->deckstr(), output);
  }

  // float MinDraft = 6;
  if (this->mindraft() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->mindraft(), output);
  }

  // float MaxDraft = 7;
  if (this->maxdraft() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->maxdraft(), output);
  }

  // int32 MaxDWT = 8;
  if (this->maxdwt() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->maxdwt(), output);
  }

  // float LCGLight = 9;
  if (this->lcglight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->lcglight(), output);
  }

  // float TCGLight = 10;
  if (this->tcglight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(10, this->tcglight(), output);
  }

  // float VCGLight = 11;
  if (this->vcglight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(11, this->vcglight(), output);
  }

  // int32 lightShip = 12;
  if (this->lightship() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(12, this->lightship(), output);
  }

  // float waterCondition = 13;
  if (this->watercondition() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(13, this->watercondition(), output);
  }

  // float tankStr = 14;
  if (this->tankstr() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(14, this->tankstr(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ship.ShipData)
}

::google::protobuf::uint8* ShipData::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ship.ShipData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string ShipName = 1;
  if (this->shipname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->shipname().data(), static_cast<int>(this->shipname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ship.ShipData.ShipName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->shipname(), target);
  }

  // float LOA = 2;
  if (this->loa() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->loa(), target);
  }

  // float height = 3;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->height(), target);
  }

  // float beam = 4;
  if (this->beam() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->beam(), target);
  }

  // float deckStr = 5;
  if (this->deckstr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->deckstr(), target);
  }

  // float MinDraft = 6;
  if (this->mindraft() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->mindraft(), target);
  }

  // float MaxDraft = 7;
  if (this->maxdraft() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->maxdraft(), target);
  }

  // int32 MaxDWT = 8;
  if (this->maxdwt() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->maxdwt(), target);
  }

  // float LCGLight = 9;
  if (this->lcglight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->lcglight(), target);
  }

  // float TCGLight = 10;
  if (this->tcglight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(10, this->tcglight(), target);
  }

  // float VCGLight = 11;
  if (this->vcglight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(11, this->vcglight(), target);
  }

  // int32 lightShip = 12;
  if (this->lightship() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(12, this->lightship(), target);
  }

  // float waterCondition = 13;
  if (this->watercondition() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(13, this->watercondition(), target);
  }

  // float tankStr = 14;
  if (this->tankstr() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(14, this->tankstr(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ship.ShipData)
  return target;
}

size_t ShipData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ship.ShipData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string ShipName = 1;
  if (this->shipname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->shipname());
  }

  // float LOA = 2;
  if (this->loa() != 0) {
    total_size += 1 + 4;
  }

  // float height = 3;
  if (this->height() != 0) {
    total_size += 1 + 4;
  }

  // float beam = 4;
  if (this->beam() != 0) {
    total_size += 1 + 4;
  }

  // float deckStr = 5;
  if (this->deckstr() != 0) {
    total_size += 1 + 4;
  }

  // float MinDraft = 6;
  if (this->mindraft() != 0) {
    total_size += 1 + 4;
  }

  // float MaxDraft = 7;
  if (this->maxdraft() != 0) {
    total_size += 1 + 4;
  }

  // int32 MaxDWT = 8;
  if (this->maxdwt() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->maxdwt());
  }

  // float LCGLight = 9;
  if (this->lcglight() != 0) {
    total_size += 1 + 4;
  }

  // float TCGLight = 10;
  if (this->tcglight() != 0) {
    total_size += 1 + 4;
  }

  // float VCGLight = 11;
  if (this->vcglight() != 0) {
    total_size += 1 + 4;
  }

  // int32 lightShip = 12;
  if (this->lightship() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->lightship());
  }

  // float waterCondition = 13;
  if (this->watercondition() != 0) {
    total_size += 1 + 4;
  }

  // float tankStr = 14;
  if (this->tankstr() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ShipData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ship.ShipData)
  GOOGLE_DCHECK_NE(&from, this);
  const ShipData* source =
      ::google::protobuf::DynamicCastToGenerated<ShipData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ship.ShipData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ship.ShipData)
    MergeFrom(*source);
  }
}

void ShipData::MergeFrom(const ShipData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ship.ShipData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.shipname().size() > 0) {

    shipname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.shipname_);
  }
  if (from.loa() != 0) {
    set_loa(from.loa());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.beam() != 0) {
    set_beam(from.beam());
  }
  if (from.deckstr() != 0) {
    set_deckstr(from.deckstr());
  }
  if (from.mindraft() != 0) {
    set_mindraft(from.mindraft());
  }
  if (from.maxdraft() != 0) {
    set_maxdraft(from.maxdraft());
  }
  if (from.maxdwt() != 0) {
    set_maxdwt(from.maxdwt());
  }
  if (from.lcglight() != 0) {
    set_lcglight(from.lcglight());
  }
  if (from.tcglight() != 0) {
    set_tcglight(from.tcglight());
  }
  if (from.vcglight() != 0) {
    set_vcglight(from.vcglight());
  }
  if (from.lightship() != 0) {
    set_lightship(from.lightship());
  }
  if (from.watercondition() != 0) {
    set_watercondition(from.watercondition());
  }
  if (from.tankstr() != 0) {
    set_tankstr(from.tankstr());
  }
}

void ShipData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ship.ShipData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ShipData::CopyFrom(const ShipData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ship.ShipData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShipData::IsInitialized() const {
  return true;
}

void ShipData::Swap(ShipData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ShipData::InternalSwap(ShipData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  shipname_.Swap(&other->shipname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(loa_, other->loa_);
  swap(height_, other->height_);
  swap(beam_, other->beam_);
  swap(deckstr_, other->deckstr_);
  swap(mindraft_, other->mindraft_);
  swap(maxdraft_, other->maxdraft_);
  swap(maxdwt_, other->maxdwt_);
  swap(lcglight_, other->lcglight_);
  swap(tcglight_, other->tcglight_);
  swap(vcglight_, other->vcglight_);
  swap(lightship_, other->lightship_);
  swap(watercondition_, other->watercondition_);
  swap(tankstr_, other->tankstr_);
}

::google::protobuf::Metadata ShipData::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Ship_2eproto);
  return ::file_level_metadata_Ship_2eproto[kIndexInFileMessages];
}


// ===================================================================

void Unit::InitAsDefaultInstance() {
}
class Unit::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Unit::kNameFieldNumber;
const int Unit::kLcgFieldNumber;
const int Unit::kTcgFieldNumber;
const int Unit::kVcgFieldNumber;
const int Unit::kLengthFieldNumber;
const int Unit::kBreadthFieldNumber;
const int Unit::kHeightFieldNumber;
const int Unit::kDensityFieldNumber;
const int Unit::kVolumeFieldNumber;
const int Unit::kTypeFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Unit::Unit()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ship.Unit)
}
Unit::Unit(const Unit& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&lcg_, &from.lcg_,
    static_cast<size_t>(reinterpret_cast<char*>(&type_) -
    reinterpret_cast<char*>(&lcg_)) + sizeof(type_));
  // @@protoc_insertion_point(copy_constructor:ship.Unit)
}

void Unit::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_Unit_Ship_2eproto.base);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&lcg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&lcg_)) + sizeof(type_));
}

Unit::~Unit() {
  // @@protoc_insertion_point(destructor:ship.Unit)
  SharedDtor();
}

void Unit::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Unit::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const Unit& Unit::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_Unit_Ship_2eproto.base);
  return *internal_default_instance();
}


void Unit::Clear() {
// @@protoc_insertion_point(message_clear_start:ship.Unit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&lcg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&type_) -
      reinterpret_cast<char*>(&lcg_)) + sizeof(type_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* Unit::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<Unit*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string Name = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("ship.Unit.Name");
        object = msg->mutable_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // float lcg = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_lcg(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float tcg = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_tcg(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float vcg = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 37) goto handle_unusual;
        msg->set_vcg(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float length = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 45) goto handle_unusual;
        msg->set_length(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float breadth = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 53) goto handle_unusual;
        msg->set_breadth(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float height = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 61) goto handle_unusual;
        msg->set_height(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float density = 8;
      case 8: {
        if (static_cast<::google::protobuf::uint8>(tag) != 69) goto handle_unusual;
        msg->set_density(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float volume = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 77) goto handle_unusual;
        msg->set_volume(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // .ship.Unit.UnitType type = 12;
      case 12: {
        if (static_cast<::google::protobuf::uint8>(tag) != 96) goto handle_unusual;
        ::google::protobuf::uint64 val = ::google::protobuf::internal::ReadVarint(&ptr);
        msg->set_type(static_cast<::ship::Unit_UnitType>(val));
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool Unit::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ship.Unit)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string Name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ship.Unit.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float lcg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &lcg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float tcg = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &tcg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float vcg = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (37 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vcg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float length = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (45 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float breadth = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (53 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &breadth_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float height = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (61 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float density = 8;
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (69 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &density_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float volume = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (77 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &volume_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // .ship.Unit.UnitType type = 12;
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (96 & 0xFF)) {
          int value = 0;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::ship::Unit_UnitType >(value));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ship.Unit)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ship.Unit)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void Unit::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ship.Unit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ship.Unit.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // float lcg = 2;
  if (this->lcg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->lcg(), output);
  }

  // float tcg = 3;
  if (this->tcg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->tcg(), output);
  }

  // float vcg = 4;
  if (this->vcg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->vcg(), output);
  }

  // float length = 5;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->length(), output);
  }

  // float breadth = 6;
  if (this->breadth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->breadth(), output);
  }

  // float height = 7;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->height(), output);
  }

  // float density = 8;
  if (this->density() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(8, this->density(), output);
  }

  // float volume = 9;
  if (this->volume() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->volume(), output);
  }

  // .ship.Unit.UnitType type = 12;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      12, this->type(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ship.Unit)
}

::google::protobuf::uint8* Unit::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ship.Unit)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ship.Unit.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // float lcg = 2;
  if (this->lcg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->lcg(), target);
  }

  // float tcg = 3;
  if (this->tcg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->tcg(), target);
  }

  // float vcg = 4;
  if (this->vcg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->vcg(), target);
  }

  // float length = 5;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->length(), target);
  }

  // float breadth = 6;
  if (this->breadth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->breadth(), target);
  }

  // float height = 7;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->height(), target);
  }

  // float density = 8;
  if (this->density() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(8, this->density(), target);
  }

  // float volume = 9;
  if (this->volume() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->volume(), target);
  }

  // .ship.Unit.UnitType type = 12;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      12, this->type(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ship.Unit)
  return target;
}

size_t Unit::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ship.Unit)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // float lcg = 2;
  if (this->lcg() != 0) {
    total_size += 1 + 4;
  }

  // float tcg = 3;
  if (this->tcg() != 0) {
    total_size += 1 + 4;
  }

  // float vcg = 4;
  if (this->vcg() != 0) {
    total_size += 1 + 4;
  }

  // float length = 5;
  if (this->length() != 0) {
    total_size += 1 + 4;
  }

  // float breadth = 6;
  if (this->breadth() != 0) {
    total_size += 1 + 4;
  }

  // float height = 7;
  if (this->height() != 0) {
    total_size += 1 + 4;
  }

  // float density = 8;
  if (this->density() != 0) {
    total_size += 1 + 4;
  }

  // float volume = 9;
  if (this->volume() != 0) {
    total_size += 1 + 4;
  }

  // .ship.Unit.UnitType type = 12;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Unit::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ship.Unit)
  GOOGLE_DCHECK_NE(&from, this);
  const Unit* source =
      ::google::protobuf::DynamicCastToGenerated<Unit>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ship.Unit)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ship.Unit)
    MergeFrom(*source);
  }
}

void Unit::MergeFrom(const Unit& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ship.Unit)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.lcg() != 0) {
    set_lcg(from.lcg());
  }
  if (from.tcg() != 0) {
    set_tcg(from.tcg());
  }
  if (from.vcg() != 0) {
    set_vcg(from.vcg());
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
  if (from.breadth() != 0) {
    set_breadth(from.breadth());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.density() != 0) {
    set_density(from.density());
  }
  if (from.volume() != 0) {
    set_volume(from.volume());
  }
  if (from.type() != 0) {
    set_type(from.type());
  }
}

void Unit::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ship.Unit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Unit::CopyFrom(const Unit& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ship.Unit)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Unit::IsInitialized() const {
  return true;
}

void Unit::Swap(Unit* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Unit::InternalSwap(Unit* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(lcg_, other->lcg_);
  swap(tcg_, other->tcg_);
  swap(vcg_, other->vcg_);
  swap(length_, other->length_);
  swap(breadth_, other->breadth_);
  swap(height_, other->height_);
  swap(density_, other->density_);
  swap(volume_, other->volume_);
  swap(type_, other->type_);
}

::google::protobuf::Metadata Unit::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Ship_2eproto);
  return ::file_level_metadata_Ship_2eproto[kIndexInFileMessages];
}


// ===================================================================

void BulkCargo::InitAsDefaultInstance() {
}
class BulkCargo::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int BulkCargo::kNameFieldNumber;
const int BulkCargo::kLcgFieldNumber;
const int BulkCargo::kTcgFieldNumber;
const int BulkCargo::kVcgFieldNumber;
const int BulkCargo::kLengthFieldNumber;
const int BulkCargo::kBreadthFieldNumber;
const int BulkCargo::kHeightFieldNumber;
const int BulkCargo::kWeightFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

BulkCargo::BulkCargo()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ship.BulkCargo)
}
BulkCargo::BulkCargo(const BulkCargo& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  ::memcpy(&lcg_, &from.lcg_,
    static_cast<size_t>(reinterpret_cast<char*>(&weight_) -
    reinterpret_cast<char*>(&lcg_)) + sizeof(weight_));
  // @@protoc_insertion_point(copy_constructor:ship.BulkCargo)
}

void BulkCargo::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_BulkCargo_Ship_2eproto.base);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&lcg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weight_) -
      reinterpret_cast<char*>(&lcg_)) + sizeof(weight_));
}

BulkCargo::~BulkCargo() {
  // @@protoc_insertion_point(destructor:ship.BulkCargo)
  SharedDtor();
}

void BulkCargo::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void BulkCargo::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const BulkCargo& BulkCargo::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_BulkCargo_Ship_2eproto.base);
  return *internal_default_instance();
}


void BulkCargo::Clear() {
// @@protoc_insertion_point(message_clear_start:ship.BulkCargo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&lcg_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&weight_) -
      reinterpret_cast<char*>(&lcg_)) + sizeof(weight_));
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* BulkCargo::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<BulkCargo*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // string Name = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        ptr = ::google::protobuf::io::ReadSize(ptr, &size);
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
        ctx->extra_parse_data().SetFieldName("ship.BulkCargo.Name");
        object = msg->mutable_name();
        if (size > end - ptr + ::google::protobuf::internal::ParseContext::kSlopBytes) {
          parser_till_end = ::google::protobuf::internal::GreedyStringParserUTF8;
          goto string_till_end;
        }
        GOOGLE_PROTOBUF_PARSER_ASSERT(::google::protobuf::internal::StringCheckUTF8(ptr, size, ctx));
        ::google::protobuf::internal::InlineGreedyStringParser(object, ptr, size, ctx);
        ptr += size;
        break;
      }
      // float lcg = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 21) goto handle_unusual;
        msg->set_lcg(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float tcg = 3;
      case 3: {
        if (static_cast<::google::protobuf::uint8>(tag) != 29) goto handle_unusual;
        msg->set_tcg(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float vcg = 4;
      case 4: {
        if (static_cast<::google::protobuf::uint8>(tag) != 37) goto handle_unusual;
        msg->set_vcg(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float length = 5;
      case 5: {
        if (static_cast<::google::protobuf::uint8>(tag) != 45) goto handle_unusual;
        msg->set_length(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float breadth = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 53) goto handle_unusual;
        msg->set_breadth(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float height = 7;
      case 7: {
        if (static_cast<::google::protobuf::uint8>(tag) != 61) goto handle_unusual;
        msg->set_height(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      // float weight = 9;
      case 9: {
        if (static_cast<::google::protobuf::uint8>(tag) != 77) goto handle_unusual;
        msg->set_weight(::google::protobuf::io::UnalignedLoad<float>(ptr));
        ptr += sizeof(float);
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
string_till_end:
  static_cast<::std::string*>(object)->clear();
  static_cast<::std::string*>(object)->reserve(size);
  goto len_delim_till_end;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool BulkCargo::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ship.BulkCargo)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string Name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "ship.BulkCargo.Name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float lcg = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (21 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &lcg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float tcg = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (29 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &tcg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float vcg = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (37 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &vcg_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float length = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (45 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &length_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float breadth = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (53 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &breadth_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float height = 7;
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (61 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &height_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float weight = 9;
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (77 & 0xFF)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &weight_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ship.BulkCargo)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ship.BulkCargo)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void BulkCargo::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ship.BulkCargo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ship.BulkCargo.Name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // float lcg = 2;
  if (this->lcg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->lcg(), output);
  }

  // float tcg = 3;
  if (this->tcg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->tcg(), output);
  }

  // float vcg = 4;
  if (this->vcg() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->vcg(), output);
  }

  // float length = 5;
  if (this->length() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->length(), output);
  }

  // float breadth = 6;
  if (this->breadth() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(6, this->breadth(), output);
  }

  // float height = 7;
  if (this->height() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(7, this->height(), output);
  }

  // float weight = 9;
  if (this->weight() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(9, this->weight(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ship.BulkCargo)
}

::google::protobuf::uint8* BulkCargo::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ship.BulkCargo)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string Name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "ship.BulkCargo.Name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // float lcg = 2;
  if (this->lcg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->lcg(), target);
  }

  // float tcg = 3;
  if (this->tcg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->tcg(), target);
  }

  // float vcg = 4;
  if (this->vcg() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->vcg(), target);
  }

  // float length = 5;
  if (this->length() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->length(), target);
  }

  // float breadth = 6;
  if (this->breadth() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(6, this->breadth(), target);
  }

  // float height = 7;
  if (this->height() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(7, this->height(), target);
  }

  // float weight = 9;
  if (this->weight() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(9, this->weight(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ship.BulkCargo)
  return target;
}

size_t BulkCargo::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ship.BulkCargo)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // string Name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // float lcg = 2;
  if (this->lcg() != 0) {
    total_size += 1 + 4;
  }

  // float tcg = 3;
  if (this->tcg() != 0) {
    total_size += 1 + 4;
  }

  // float vcg = 4;
  if (this->vcg() != 0) {
    total_size += 1 + 4;
  }

  // float length = 5;
  if (this->length() != 0) {
    total_size += 1 + 4;
  }

  // float breadth = 6;
  if (this->breadth() != 0) {
    total_size += 1 + 4;
  }

  // float height = 7;
  if (this->height() != 0) {
    total_size += 1 + 4;
  }

  // float weight = 9;
  if (this->weight() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void BulkCargo::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ship.BulkCargo)
  GOOGLE_DCHECK_NE(&from, this);
  const BulkCargo* source =
      ::google::protobuf::DynamicCastToGenerated<BulkCargo>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ship.BulkCargo)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ship.BulkCargo)
    MergeFrom(*source);
  }
}

void BulkCargo::MergeFrom(const BulkCargo& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ship.BulkCargo)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.lcg() != 0) {
    set_lcg(from.lcg());
  }
  if (from.tcg() != 0) {
    set_tcg(from.tcg());
  }
  if (from.vcg() != 0) {
    set_vcg(from.vcg());
  }
  if (from.length() != 0) {
    set_length(from.length());
  }
  if (from.breadth() != 0) {
    set_breadth(from.breadth());
  }
  if (from.height() != 0) {
    set_height(from.height());
  }
  if (from.weight() != 0) {
    set_weight(from.weight());
  }
}

void BulkCargo::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ship.BulkCargo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void BulkCargo::CopyFrom(const BulkCargo& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ship.BulkCargo)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool BulkCargo::IsInitialized() const {
  return true;
}

void BulkCargo::Swap(BulkCargo* other) {
  if (other == this) return;
  InternalSwap(other);
}
void BulkCargo::InternalSwap(BulkCargo* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(lcg_, other->lcg_);
  swap(tcg_, other->tcg_);
  swap(vcg_, other->vcg_);
  swap(length_, other->length_);
  swap(breadth_, other->breadth_);
  swap(height_, other->height_);
  swap(weight_, other->weight_);
}

::google::protobuf::Metadata BulkCargo::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Ship_2eproto);
  return ::file_level_metadata_Ship_2eproto[kIndexInFileMessages];
}


// ===================================================================

void ShipBodyData::InitAsDefaultInstance() {
}
class ShipBodyData::HasBitSetters {
 public:
};

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ShipBodyData::kShipdataFieldNumber;
const int ShipBodyData::kUnitFieldNumber;
const int ShipBodyData::kBulkFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ShipBodyData::ShipBodyData()
  : ::google::protobuf::Message(), _internal_metadata_(nullptr) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:ship.ShipBodyData)
}
ShipBodyData::ShipBodyData(const ShipBodyData& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(nullptr),
      shipdata_(from.shipdata_),
      unit_(from.unit_),
      bulk_(from.bulk_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  // @@protoc_insertion_point(copy_constructor:ship.ShipBodyData)
}

void ShipBodyData::SharedCtor() {
  ::google::protobuf::internal::InitSCC(
      &scc_info_ShipBodyData_Ship_2eproto.base);
}

ShipBodyData::~ShipBodyData() {
  // @@protoc_insertion_point(destructor:ship.ShipBodyData)
  SharedDtor();
}

void ShipBodyData::SharedDtor() {
}

void ShipBodyData::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ShipBodyData& ShipBodyData::default_instance() {
  ::google::protobuf::internal::InitSCC(&::scc_info_ShipBodyData_Ship_2eproto.base);
  return *internal_default_instance();
}


void ShipBodyData::Clear() {
// @@protoc_insertion_point(message_clear_start:ship.ShipBodyData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  shipdata_.Clear();
  unit_.Clear();
  bulk_.Clear();
  _internal_metadata_.Clear();
}

#if GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
const char* ShipBodyData::_InternalParse(const char* begin, const char* end, void* object,
                  ::google::protobuf::internal::ParseContext* ctx) {
  auto msg = static_cast<ShipBodyData*>(object);
  ::google::protobuf::int32 size; (void)size;
  int depth; (void)depth;
  ::google::protobuf::uint32 tag;
  ::google::protobuf::internal::ParseFunc parser_till_end; (void)parser_till_end;
  auto ptr = begin;
  while (ptr < end) {
    ptr = ::google::protobuf::io::Parse32(ptr, &tag);
    GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
    switch (tag >> 3) {
      // repeated .ship.ShipData shipdata = 1;
      case 1: {
        if (static_cast<::google::protobuf::uint8>(tag) != 10) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::ship::ShipData::_InternalParse;
          object = msg->add_shipdata();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 10 && (ptr += 1));
        break;
      }
      // repeated .ship.Unit unit = 2;
      case 2: {
        if (static_cast<::google::protobuf::uint8>(tag) != 18) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::ship::Unit::_InternalParse;
          object = msg->add_unit();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 18 && (ptr += 1));
        break;
      }
      // repeated .ship.BulkCargo bulk = 6;
      case 6: {
        if (static_cast<::google::protobuf::uint8>(tag) != 50) goto handle_unusual;
        do {
          ptr = ::google::protobuf::io::ReadSize(ptr, &size);
          GOOGLE_PROTOBUF_PARSER_ASSERT(ptr);
          parser_till_end = ::ship::BulkCargo::_InternalParse;
          object = msg->add_bulk();
          if (size > end - ptr) goto len_delim_till_end;
          ptr += size;
          GOOGLE_PROTOBUF_PARSER_ASSERT(ctx->ParseExactRange(
              {parser_till_end, object}, ptr - size, ptr));
          if (ptr >= end) break;
        } while ((::google::protobuf::io::UnalignedLoad<::google::protobuf::uint64>(ptr) & 255) == 50 && (ptr += 1));
        break;
      }
      default: {
      handle_unusual:
        if ((tag & 7) == 4 || tag == 0) {
          ctx->EndGroup(tag);
          return ptr;
        }
        auto res = UnknownFieldParse(tag, {_InternalParse, msg},
          ptr, end, msg->_internal_metadata_.mutable_unknown_fields(), ctx);
        ptr = res.first;
        GOOGLE_PROTOBUF_PARSER_ASSERT(ptr != nullptr);
        if (res.second) return ptr;
      }
    }  // switch
  }  // while
  return ptr;
len_delim_till_end:
  return ctx->StoreAndTailCall(ptr, end, {_InternalParse, msg},
                               {parser_till_end, object}, size);
}
#else  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER
bool ShipBodyData::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!PROTOBUF_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:ship.ShipBodyData)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .ship.ShipData shipdata = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (10 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_shipdata()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ship.Unit unit = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (18 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_unit()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .ship.BulkCargo bulk = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) == (50 & 0xFF)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_bulk()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:ship.ShipBodyData)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:ship.ShipBodyData)
  return false;
#undef DO_
}
#endif  // GOOGLE_PROTOBUF_ENABLE_EXPERIMENTAL_PARSER

void ShipBodyData::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:ship.ShipBodyData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ship.ShipData shipdata = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->shipdata_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1,
      this->shipdata(static_cast<int>(i)),
      output);
  }

  // repeated .ship.Unit unit = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->unit_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2,
      this->unit(static_cast<int>(i)),
      output);
  }

  // repeated .ship.BulkCargo bulk = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bulk_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->bulk(static_cast<int>(i)),
      output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:ship.ShipBodyData)
}

::google::protobuf::uint8* ShipBodyData::InternalSerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:ship.ShipBodyData)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // repeated .ship.ShipData shipdata = 1;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->shipdata_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->shipdata(static_cast<int>(i)), target);
  }

  // repeated .ship.Unit unit = 2;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->unit_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        2, this->unit(static_cast<int>(i)), target);
  }

  // repeated .ship.BulkCargo bulk = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->bulk_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->bulk(static_cast<int>(i)), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:ship.ShipBodyData)
  return target;
}

size_t ShipBodyData::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:ship.ShipBodyData)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .ship.ShipData shipdata = 1;
  {
    unsigned int count = static_cast<unsigned int>(this->shipdata_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->shipdata(static_cast<int>(i)));
    }
  }

  // repeated .ship.Unit unit = 2;
  {
    unsigned int count = static_cast<unsigned int>(this->unit_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->unit(static_cast<int>(i)));
    }
  }

  // repeated .ship.BulkCargo bulk = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->bulk_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->bulk(static_cast<int>(i)));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ShipBodyData::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:ship.ShipBodyData)
  GOOGLE_DCHECK_NE(&from, this);
  const ShipBodyData* source =
      ::google::protobuf::DynamicCastToGenerated<ShipBodyData>(
          &from);
  if (source == nullptr) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:ship.ShipBodyData)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:ship.ShipBodyData)
    MergeFrom(*source);
  }
}

void ShipBodyData::MergeFrom(const ShipBodyData& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:ship.ShipBodyData)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  shipdata_.MergeFrom(from.shipdata_);
  unit_.MergeFrom(from.unit_);
  bulk_.MergeFrom(from.bulk_);
}

void ShipBodyData::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:ship.ShipBodyData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ShipBodyData::CopyFrom(const ShipBodyData& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:ship.ShipBodyData)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ShipBodyData::IsInitialized() const {
  return true;
}

void ShipBodyData::Swap(ShipBodyData* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ShipBodyData::InternalSwap(ShipBodyData* other) {
  using std::swap;
  _internal_metadata_.Swap(&other->_internal_metadata_);
  CastToBase(&shipdata_)->InternalSwap(CastToBase(&other->shipdata_));
  CastToBase(&unit_)->InternalSwap(CastToBase(&other->unit_));
  CastToBase(&bulk_)->InternalSwap(CastToBase(&other->bulk_));
}

::google::protobuf::Metadata ShipBodyData::GetMetadata() const {
  ::google::protobuf::internal::AssignDescriptors(&::assign_descriptors_table_Ship_2eproto);
  return ::file_level_metadata_Ship_2eproto[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace ship
namespace google {
namespace protobuf {
template<> PROTOBUF_NOINLINE ::ship::ShipData* Arena::CreateMaybeMessage< ::ship::ShipData >(Arena* arena) {
  return Arena::CreateInternal< ::ship::ShipData >(arena);
}
template<> PROTOBUF_NOINLINE ::ship::Unit* Arena::CreateMaybeMessage< ::ship::Unit >(Arena* arena) {
  return Arena::CreateInternal< ::ship::Unit >(arena);
}
template<> PROTOBUF_NOINLINE ::ship::BulkCargo* Arena::CreateMaybeMessage< ::ship::BulkCargo >(Arena* arena) {
  return Arena::CreateInternal< ::ship::BulkCargo >(arena);
}
template<> PROTOBUF_NOINLINE ::ship::ShipBodyData* Arena::CreateMaybeMessage< ::ship::ShipBodyData >(Arena* arena) {
  return Arena::CreateInternal< ::ship::ShipBodyData >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
#include <google/protobuf/port_undef.inc>
